# This is a basic workflow to help you get started with Actions

name: sample CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Make temp dir
        run: mkdir downloads
      
      - name: Configure ns3
        run: ./waf configure --enable-examples
      
      - name: Compile ns3 files
        run: ./waf

      - name: Run bash script simulation(50 pairs)
        run: ./autosimulationGrid.sh

      - name: Upload Artifact(output csv)
        uses: actions/upload-artifact@v2
        with:
          name: grid-output
          path: downloads

      # Runs a set of commands using the runners shell
      # - name: Bash script
      #   run: chmod +x sim_test.sh | ./sim_test.sh
      #- name: Run simulation(multi)
      #  run: ./waf --run scratch/sim2_random
      #  run: ./waf --run "scratch/finalsimulationGrid --sourceNode=0 --sinkNode=10 --numPackets=2000"
